# Principal Component Analysis of Grimm Brothers

## Setup and Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [2]:
import plotly.express as px
import plotly.io as pio

In [3]:
TFIDF = pd.read_csv('data/pg2591-TFIDF.csv',index_col=0)
TFIDF.head()

,king,man,old,we,upon,father,himself,shall,take,cried,...,appear,cooking,grass,backwards,finding,doors,sides,searched,started,hide
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0.111674,0.004770,0.00420,0.004200,0.014623,0.102368,0.011775,0.014623,0.010177,0.021935,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028603
BRIAR ROSE,0.263257,0.017991,0.06337,0.000000,0.041367,0.000000,0.000000,0.020683,0.012795,0.006894,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT AND MOUSE IN PARTNERSHIP,0.000000,0.000000,0.00000,0.038154,0.004744,0.000000,0.000000,0.009488,0.004402,0.014232,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT-SKIN,0.452256,0.000000,0.00000,0.021486,0.014026,0.035704,0.000000,0.004675,0.026031,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.036579
CLEVER ELSIE,0.000000,0.038482,0.00000,0.081325,0.000000,0.030031,0.000000,0.035392,0.000000,0.011797,...,0.046151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [4]:
DTM = pd.read_csv('data/pg2591-DTM.csv',index_col=0)
DTM.head()

,1,2,3,_jug,_my_,a,abashed,abide,able,abode,...,yonder,you,young,younger,youngest,your,yours,yourself,yourselves,youth
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0,0,0,0,1,21,0,0,0,0,...,0,24,0,0,0,3,0,0,0,0
BRIAR ROSE,0,0,0,0,0,33,0,0,0,0,...,0,2,1,0,0,2,0,0,0,0
CAT AND MOUSE IN PARTNERSHIP,0,0,0,0,0,17,0,0,0,0,...,0,21,0,0,0,4,1,1,0,0
CAT-SKIN,0,0,0,0,0,46,0,0,0,0,...,0,20,0,0,0,1,0,0,0,0
CLEVER ELSIE,0,0,0,0,0,23,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0

In [5]:
LIB = pd.read_csv('data/pg2591-LIB.csv',index_col=0)
LIB.head()

                          volume
doc_title
THE GOLDEN BIRD                1
HANS IN LUCK                   1
JORINDA AND JORINDEL           1
THE TRAVELLING MUSICIANS       1
OLD SULTAN                     1

## DCM

In [6]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

,PC0,PC1,PC2,PC3,PC4
doc_title,,,,,
ASHPUTTEL,-0.149593,-0.117990,0.077601,0.075956,-0.219760
BRIAR ROSE,-0.225390,-0.240806,0.198710,-0.034328,-0.009417
CAT AND MOUSE IN PARTNERSHIP,0.298417,0.086533,-0.215809,-0.168872,-0.085327
CAT-SKIN,-0.257712,-0.272943,0.270890,-0.167645,-0.158265
CLEVER ELSIE,0.007553,0.155673,-0.167320,-0.165868,-0.019563
...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811440,-0.110868,0.157879,-0.013642,-0.017292
THE WHITE SNAKE,-0.142331,-0.122720,0.054792,-0.069637,-0.078770
THE WILLOW-WREN AND THE BEAR,0.286636,0.116845,0.449131,0.032663,0.230606
THE WOLF AND THE SEVEN LITTLE KIDS,0.155402,0.531831,0.467235,0.203696,-0.045674
TOM THUMB,0.030378,0.312400,0.135173,0.261536,-0.254967

In [7]:
## Make Loading

In [8]:
LOADING = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
LOADING.columns = ["PC{}".format(i) for i in LOADING.columns]
LOADING.index = TFIDF.columns
LOADING.index.name = 'term_str'
LOADING.head()

               PC0       PC1       PC2       PC3       PC4
term_str
king     -0.054912 -0.067084  0.052747 -0.025423 -0.027222
man      -0.010366 -0.002335 -0.004315 -0.003024  0.003783
old       0.001094  0.003781  0.004786 -0.002895  0.000975
we       -0.001012  0.010622  0.003814 -0.003654  0.000846
upon     -0.003013 -0.001580 -0.004448  0.009206 -0.000780

## Get Top 5 Postive Terms for PC0

In [9]:
LOADING.sort_values(by='PC0',ascending=False).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163085 -0.076841  0.022097 -0.005698  0.016973
cat       0.083834 -0.009609 -0.010386 -0.015809 -0.007443
mr        0.050418 -0.017096  0.002032 -0.006130  0.005786
wolf      0.048082  0.086991  0.082180  0.049640 -0.034956
mouse     0.021250  0.012351 -0.025565 -0.019061 -0.011073

## Get Top 5 Negatuve Terms for PC1

In [10]:
LOADING.sort_values(by='PC1',ascending=True).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163085 -0.076841  0.022097 -0.005698  0.016973
king     -0.054912 -0.067084  0.052747 -0.025423 -0.027222
princess -0.018986 -0.043415  0.011819  0.035979 -0.009749
prince   -0.021696 -0.027729  0.007250  0.034589 -0.006905
twelve   -0.015513 -0.025032  0.013596  0.002562 -0.003144

## Creating Visuals

## Getting DOC Table ready

In [11]:
DOC = DTM.sum(1).to_frame('n_tokens')
DOC['n_types'] = DTM.astype('bool').sum(1)
DOC['pkr'] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB['volume'])

In [12]:
NEW=DCM.join(DOC)
NEW

,PC0,PC1,PC2,PC3,PC4,n_tokens,n_types,pkr,volume
doc_title,,,,,,,,,
ASHPUTTEL,-0.149593,-0.117990,0.077601,0.075956,-0.219760,2589,506,0.195442,1
BRIAR ROSE,-0.225390,-0.240806,0.198710,-0.034328,-0.009417,1518,453,0.298419,1
CAT AND MOUSE IN PARTNERSHIP,0.298417,0.086533,-0.215809,-0.168872,-0.085327,985,344,0.349239,1
CAT-SKIN,-0.257712,-0.272943,0.270890,-0.167645,-0.158265,2136,470,0.220037,1
CLEVER ELSIE,0.007553,0.155673,-0.167320,-0.165868,-0.019563,1338,338,0.252616,1
...,...,...,...,...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811440,-0.110868,0.157879,-0.013642,-0.017292,376,174,0.462766,1
THE WHITE SNAKE,-0.142331,-0.122720,0.054792,-0.069637,-0.078770,1613,534,0.331060,1
THE WILLOW-WREN AND THE BEAR,0.286636,0.116845,0.449131,0.032663,0.230606,917,339,0.369684,1
THE WOLF AND THE SEVEN LITTLE KIDS,0.155402,0.531831,0.467235,0.203696,-0.045674,1102,336,0.304900,1
TOM THUMB,0.030378,0.312400,0.135173,0.261536,-0.254967,2541,612,0.240850,1

### Importing Functions

In [23]:
def vis_pcs(a, b,DCM, col='doc_label'):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DOC[col].astype('category'), 
        hover_name=DCM.index,
        marginal_x='box', 
        height=1000, 
        width=1200)
    fig.show()

In [14]:
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [15]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

In [24]:
vis_pcs(0,1,NEW,col='volume')

The new additions in Volume II are all on the negative side for PC0 and PC1. Volume I is similar but also has stories that has more positive componets. The Fox and the Horse seems to be an outlier in Volume 1.