# Principal Component Analysis of Grimm Brothers

## Setup and Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [3]:
import plotly.express as px
import plotly.io as pio

In [4]:
TFIDF = pd.read_csv('data/pg2591-TFIDF.csv',index_col=0)
TFIDF.head()

,king,man,old,we,upon,father,himself,shall,take,cried,...,appear,cooking,grass,backwards,finding,doors,sides,searched,started,hide
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0.111674,0.004770,0.00420,0.004200,0.014623,0.102368,0.011775,0.014623,0.010177,0.021935,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028603
BRIAR ROSE,0.263257,0.017991,0.06337,0.000000,0.041367,0.000000,0.000000,0.020683,0.012795,0.006894,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT AND MOUSE IN PARTNERSHIP,0.000000,0.000000,0.00000,0.038154,0.004744,0.000000,0.000000,0.009488,0.004402,0.014232,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT-SKIN,0.452256,0.000000,0.00000,0.021486,0.014026,0.035704,0.000000,0.004675,0.026031,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.036579
CLEVER ELSIE,0.000000,0.038482,0.00000,0.081325,0.000000,0.030031,0.000000,0.035392,0.000000,0.011797,...,0.046151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [5]:
DTM = pd.read_csv('data/pg2591-DTM.csv',index_col=0)
DTM.head()

,1,2,3,_jug,_my_,a,abashed,abide,able,abode,...,yonder,you,young,younger,youngest,your,yours,yourself,yourselves,youth
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0,0,0,0,1,21,0,0,0,0,...,0,24,0,0,0,3,0,0,0,0
BRIAR ROSE,0,0,0,0,0,33,0,0,0,0,...,0,2,1,0,0,2,0,0,0,0
CAT AND MOUSE IN PARTNERSHIP,0,0,0,0,0,17,0,0,0,0,...,0,21,0,0,0,4,1,1,0,0
CAT-SKIN,0,0,0,0,0,46,0,0,0,0,...,0,20,0,0,0,1,0,0,0,0
CLEVER ELSIE,0,0,0,0,0,23,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0

In [6]:
LIB = pd.read_csv('data/pg2591-LIB.csv',index_col=0)
LIB.head()

                          volume
doc_title
THE GOLDEN BIRD                1
HANS IN LUCK                   1
JORINDA AND JORINDEL           1
THE TRAVELLING MUSICIANS       1
OLD SULTAN                     1

## DCM

In [7]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

,PC0,PC1,PC2,PC3,PC4
doc_title,,,,,
ASHPUTTEL,-0.149596,-0.117989,0.079371,0.067209,-0.200337
BRIAR ROSE,-0.225359,-0.240708,0.199851,-0.026808,-0.025581
CAT AND MOUSE IN PARTNERSHIP,0.298438,0.085725,-0.202121,-0.180105,-0.028263
CAT-SKIN,-0.257702,-0.273391,0.274076,-0.153942,-0.163532
CLEVER ELSIE,0.007587,0.156407,-0.170091,-0.154175,-0.043754
...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811444,-0.110817,0.156594,-0.012338,-0.014987
THE WHITE SNAKE,-0.142335,-0.123665,0.052645,-0.054405,-0.092994
THE WILLOW-WREN AND THE BEAR,0.286640,0.116825,0.449099,0.041790,0.220064
THE WOLF AND THE SEVEN LITTLE KIDS,0.155402,0.531417,0.466994,0.215825,-0.043995
TOM THUMB,0.030391,0.313140,0.125047,0.263755,-0.261101

In [8]:
## Make Loading

In [9]:
LOADING = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
LOADING.columns = ["PC{}".format(i) for i in LOADING.columns]
LOADING.index = TFIDF.columns
LOADING.index.name = 'term_str'
LOADING.head()

               PC0       PC1       PC2       PC3       PC4
term_str
king     -0.054912 -0.067164  0.053043 -0.023301 -0.027188
man      -0.010365 -0.002316 -0.004611 -0.003451  0.003594
old       0.001093  0.003784  0.004885 -0.003542  0.001080
we       -0.001011  0.010658  0.003250 -0.003528 -0.000715
upon     -0.003013 -0.001556 -0.004843  0.008943 -0.000879

## Get Top 5 Postive Terms for PC0

In [10]:
LOADING.sort_values(by='PC0',ascending=False).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163084 -0.076810  0.021663 -0.005705  0.013519
cat       0.083835 -0.009562 -0.010500 -0.016707 -0.004141
mr        0.050419 -0.017007  0.001397 -0.006281  0.004367
wolf      0.048082  0.086937  0.081922  0.051568 -0.033416
mouse     0.021255  0.012144 -0.022808 -0.020519 -0.002778

## Get Top 5 Negative Terms for PC1

In [11]:
LOADING.sort_values(by='PC1',ascending=True).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163084 -0.076810  0.021663 -0.005705  0.013519
king     -0.054912 -0.067164  0.053043 -0.023301 -0.027188
princess -0.018991 -0.043503  0.012488  0.037761 -0.010807
prince   -0.021698 -0.027698  0.006817  0.034870 -0.006335
twelve   -0.015513 -0.025029  0.013744  0.001472 -0.001267

## Creating Visuals

## Getting DOC Table ready

In [12]:
DOC = DTM.sum(1).to_frame('n_tokens')
DOC['n_types'] = DTM.astype('bool').sum(1)
DOC['pkr'] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB['volume'])

In [13]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

In [14]:
NEW=DCM.join(DOC)
NEW

,PC0,PC1,PC2,PC3,PC4,n_tokens,n_types,pkr,volume
doc_title,,,,,,,,,
ASHPUTTEL,-0.149596,-0.117989,0.079371,0.067209,-0.200337,2589,506,0.195442,1
BRIAR ROSE,-0.225359,-0.240708,0.199851,-0.026808,-0.025581,1518,453,0.298419,1
CAT AND MOUSE IN PARTNERSHIP,0.298438,0.085725,-0.202121,-0.180105,-0.028263,985,344,0.349239,1
CAT-SKIN,-0.257702,-0.273391,0.274076,-0.153942,-0.163532,2136,470,0.220037,1
CLEVER ELSIE,0.007587,0.156407,-0.170091,-0.154175,-0.043754,1338,338,0.252616,1
...,...,...,...,...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811444,-0.110817,0.156594,-0.012338,-0.014987,376,174,0.462766,1
THE WHITE SNAKE,-0.142335,-0.123665,0.052645,-0.054405,-0.092994,1613,534,0.331060,1
THE WILLOW-WREN AND THE BEAR,0.286640,0.116825,0.449099,0.041790,0.220064,917,339,0.369684,2
THE WOLF AND THE SEVEN LITTLE KIDS,0.155402,0.531417,0.466994,0.215825,-0.043995,1102,336,0.304900,1
TOM THUMB,0.030391,0.313140,0.125047,0.263755,-0.261101,2541,612,0.240850,1

### Importing Functions

In [25]:
def vis_pcs(a, b,DCM, col='doc_label'):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DOC[col].astype('category'), 
        hover_name=DCM.index,
        marginal_x='box', 
        height=1000, 
        width=1200)
    return fig

In [16]:
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [17]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

### Visualize PCA 0 and 1

In [26]:
fig1=vis_pcs(0,1,NEW,col='volume')
fig1.write_image('output/p2591-PC1.png')
fig1.show()

The new additions in Volume II are all on the negative side for PC0 and PC1. Volume I is similar but also has stories that has more positive componets. This suggests that Volume I is more varied in PC0 and PC1 than Volume II.

### Visualize Loadings 0 and 1

In [ ]:
fig2=vis_loadings(LOADING,0,1)
fig2.write_image('output/p2591-LOADING1.png')
fig2.show()

Most words seems to be in a huge cluster around the middle. There are some other clusters. For example the bottom left seems to have royal words like prince and kings. Right above the cluster seems to have family/identity words like mother and children.

## VIS PCA 2,3

In [27]:
fig3=vis_pcs(2,3,NEW,col='volume')
fig3.write_image('output/p2591-PC2.png')
fig3.show()

Both Volume I and Volume II seem to be well to be evenly distriuted around PC2 and PC3 with even spread in the postive and negative side. Again Volume II is less varied - as it has a shorter whiskser - with PC2 and PC3 values, this could be due to Volume II having less stories

## VIS LOADINGS 2,3

In [28]:
fig4=vis_loadings(LOADING,2,3)
fig4.write_image('output/p2591-LOADING2.png')
fig4.show()

Like the last loading, this one also have a huge clusters around the origin and several smaller clusters. This one seems to more smaller custers than the loadings of PC0 and PC1. I did notice similar separatuion class. Working class terms - cookm huntsmen, etc -have negative PC3 value, while prince and princess - royal words - are on the postive side of PC3. There are clear outliers though with king and queen having negative PC3. SO maybe these PC are a bit more complex than just social class.