# Principal Component Analysis of Grimm Brothers

## Setup and Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [2]:
import plotly.express as px
import plotly.io as pio

In [3]:
TFIDF = pd.read_csv('data/pg2591-TFIDF.csv',index_col=0)
TFIDF.head()

,king,man,old,we,upon,father,himself,shall,take,cried,...,appear,cooking,grass,backwards,finding,doors,sides,searched,started,hide
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0.111674,0.004770,0.00420,0.004200,0.014623,0.102368,0.011775,0.014623,0.010177,0.021935,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028603
BRIAR ROSE,0.263257,0.017991,0.06337,0.000000,0.041367,0.000000,0.000000,0.020683,0.012795,0.006894,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT AND MOUSE IN PARTNERSHIP,0.000000,0.000000,0.00000,0.038154,0.004744,0.000000,0.000000,0.009488,0.004402,0.014232,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT-SKIN,0.452256,0.000000,0.00000,0.021486,0.014026,0.035704,0.000000,0.004675,0.026031,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.036579
CLEVER ELSIE,0.000000,0.038482,0.00000,0.081325,0.000000,0.030031,0.000000,0.035392,0.000000,0.011797,...,0.046151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [4]:
DTM = pd.read_csv('data/pg2591-DTM.csv',index_col=0)
DTM.head()

,1,2,3,_jug,_my_,a,abashed,abide,able,abode,...,yonder,you,young,younger,youngest,your,yours,yourself,yourselves,youth
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0,0,0,0,1,21,0,0,0,0,...,0,24,0,0,0,3,0,0,0,0
BRIAR ROSE,0,0,0,0,0,33,0,0,0,0,...,0,2,1,0,0,2,0,0,0,0
CAT AND MOUSE IN PARTNERSHIP,0,0,0,0,0,17,0,0,0,0,...,0,21,0,0,0,4,1,1,0,0
CAT-SKIN,0,0,0,0,0,46,0,0,0,0,...,0,20,0,0,0,1,0,0,0,0
CLEVER ELSIE,0,0,0,0,0,23,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0

In [5]:
LIB = pd.read_csv('data/pg2591-LIB.csv',index_col=0)
LIB.head()

                          volume
doc_title
THE GOLDEN BIRD                1
HANS IN LUCK                   1
JORINDA AND JORINDEL           1
THE TRAVELLING MUSICIANS       1
OLD SULTAN                     1

## DCM

In [6]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

,PC0,PC1,PC2,PC3,PC4
doc_title,,,,,
ASHPUTTEL,-0.149575,-0.117873,0.082712,0.066956,-0.203970
BRIAR ROSE,-0.225376,-0.240574,0.195422,-0.034782,-0.028181
CAT AND MOUSE IN PARTNERSHIP,0.298438,0.085764,-0.204514,-0.177425,-0.033820
CAT-SKIN,-0.257712,-0.273104,0.270071,-0.164791,-0.163653
CLEVER ELSIE,0.007566,0.156383,-0.179128,-0.155514,-0.029820
...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811444,-0.111001,0.156473,-0.013065,-0.017413
THE WHITE SNAKE,-0.142341,-0.122297,0.047815,-0.061502,-0.091007
THE WILLOW-WREN AND THE BEAR,0.286642,0.117119,0.446907,0.032598,0.209252
THE WOLF AND THE SEVEN LITTLE KIDS,0.155400,0.531526,0.465935,0.208707,-0.042936
TOM THUMB,0.030379,0.312770,0.130698,0.266355,-0.259050

In [7]:
## Make Loading

In [8]:
LOADING = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
LOADING.columns = ["PC{}".format(i) for i in LOADING.columns]
LOADING.index = TFIDF.columns
LOADING.index.name = 'term_str'
LOADING.head()

               PC0       PC1       PC2       PC3       PC4
term_str
king     -0.054914 -0.067158  0.052439 -0.024425 -0.027670
man      -0.010365 -0.002346 -0.004496 -0.002781  0.003858
old       0.001094  0.003756  0.005126 -0.003037  0.001247
we       -0.001013  0.010645  0.003405 -0.003191 -0.000253
upon     -0.003014 -0.001574 -0.004521  0.009213 -0.001122

## Get Top 5 Postive Terms for PC0

In [9]:
LOADING.sort_values(by='PC0',ascending=False).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163084 -0.076824  0.021646 -0.005314  0.014758
cat       0.083835 -0.009643 -0.010030 -0.016284 -0.005612
mr        0.050419 -0.017059  0.001613 -0.006122  0.004120
wolf      0.048082  0.086941  0.081951  0.050220 -0.033436
mouse     0.021255  0.012219 -0.023543 -0.020420 -0.002356

## Get Top 5 Negatuve Terms for PC1

In [10]:
LOADING.sort_values(by='PC1',ascending=True).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163084 -0.076824  0.021646 -0.005314  0.014758
king     -0.054914 -0.067158  0.052439 -0.024425 -0.027670
princess -0.018992 -0.043488  0.012593  0.037240 -0.008184
prince   -0.021696 -0.027716  0.007121  0.034871 -0.006129
twelve   -0.015512 -0.025076  0.013969  0.001933 -0.001967

## Creating Visuals

## Getting DOC Table ready

In [11]:
DOC = DTM.sum(1).to_frame('n_tokens')
DOC['n_types'] = DTM.astype('bool').sum(1)
DOC['pkr'] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB['volume'])

In [12]:
NEW=DCM.join(DOC)
NEW

,PC0,PC1,PC2,PC3,PC4,n_tokens,n_types,pkr,volume
doc_title,,,,,,,,,
ASHPUTTEL,-0.149575,-0.117873,0.082712,0.066956,-0.203970,2589,506,0.195442,1
BRIAR ROSE,-0.225376,-0.240574,0.195422,-0.034782,-0.028181,1518,453,0.298419,1
CAT AND MOUSE IN PARTNERSHIP,0.298438,0.085764,-0.204514,-0.177425,-0.033820,985,344,0.349239,1
CAT-SKIN,-0.257712,-0.273104,0.270071,-0.164791,-0.163653,2136,470,0.220037,1
CLEVER ELSIE,0.007566,0.156383,-0.179128,-0.155514,-0.029820,1338,338,0.252616,1
...,...,...,...,...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811444,-0.111001,0.156473,-0.013065,-0.017413,376,174,0.462766,1
THE WHITE SNAKE,-0.142341,-0.122297,0.047815,-0.061502,-0.091007,1613,534,0.331060,1
THE WILLOW-WREN AND THE BEAR,0.286642,0.117119,0.446907,0.032598,0.209252,917,339,0.369684,2
THE WOLF AND THE SEVEN LITTLE KIDS,0.155400,0.531526,0.465935,0.208707,-0.042936,1102,336,0.304900,1
TOM THUMB,0.030379,0.312770,0.130698,0.266355,-0.259050,2541,612,0.240850,1

### Importing Functions

In [13]:
def vis_pcs(a, b,DCM, col='doc_label'):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DOC[col].astype('category'), 
        hover_name=DCM.index,
        marginal_x='box', 
        height=1000, 
        width=1200)
    fig.show()

In [20]:
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [15]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

### Visualize PCA

In [16]:
vis_pcs(0,1,NEW,col='volume')

The new additions in Volume II are all on the negative side for PC0 and PC1. Volume I is similar but also has stories that has more positive componets. This suggests that Volume I is more varied in PC0 and PC1 than Volume II.

### Visualize Loadings

In [23]:
vis_loadings(LOADING,0,1)

Most words seems to be in a huge cluster around the middle. There are some other clusters. For example the bottom left seems to have royal words like prince and kings. Right above the cluster seems to have family/identity words like mother and children.