# Principal Component Analysis of Grimm Brothers

## Setup and Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [2]:
import plotly.express as px
import plotly.io as pio

In [3]:
TFIDF = pd.read_csv('data/pg2591-TFIDF.csv',index_col=0)
TFIDF.head()

,king,man,old,we,upon,father,himself,shall,take,cried,...,appear,cooking,grass,backwards,finding,doors,sides,searched,started,hide
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0.111674,0.004770,0.00420,0.004200,0.014623,0.102368,0.011775,0.014623,0.010177,0.021935,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028603
BRIAR ROSE,0.263257,0.017991,0.06337,0.000000,0.041367,0.000000,0.000000,0.020683,0.012795,0.006894,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT AND MOUSE IN PARTNERSHIP,0.000000,0.000000,0.00000,0.038154,0.004744,0.000000,0.000000,0.009488,0.004402,0.014232,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT-SKIN,0.452256,0.000000,0.00000,0.021486,0.014026,0.035704,0.000000,0.004675,0.026031,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.036579
CLEVER ELSIE,0.000000,0.038482,0.00000,0.081325,0.000000,0.030031,0.000000,0.035392,0.000000,0.011797,...,0.046151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [4]:
DTM = pd.read_csv('data/pg2591-DTM.csv',index_col=0)
DTM.head()

,1,2,3,_jug,_my_,a,abashed,abide,able,abode,...,yonder,you,young,younger,youngest,your,yours,yourself,yourselves,youth
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0,0,0,0,1,21,0,0,0,0,...,0,24,0,0,0,3,0,0,0,0
BRIAR ROSE,0,0,0,0,0,33,0,0,0,0,...,0,2,1,0,0,2,0,0,0,0
CAT AND MOUSE IN PARTNERSHIP,0,0,0,0,0,17,0,0,0,0,...,0,21,0,0,0,4,1,1,0,0
CAT-SKIN,0,0,0,0,0,46,0,0,0,0,...,0,20,0,0,0,1,0,0,0,0
CLEVER ELSIE,0,0,0,0,0,23,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0

In [5]:
LIB = pd.read_csv('data/pg2591-LIB.csv',index_col=0)
LIB.head()

                          volume  n_tokens  n_paras
doc_title
THE GOLDEN BIRD                1      2815       19
HANS IN LUCK                   1      2736       19
JORINDA AND JORINDEL           1      1238       16
THE TRAVELLING MUSICIANS       1      1555        8
OLD SULTAN                     1       974        5

## DCM

In [6]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

,PC0,PC1,PC2,PC3,PC4
doc_title,,,,,
ASHPUTTEL,-0.149570,-0.118080,0.082594,0.067198,-0.198049
BRIAR ROSE,-0.225364,-0.240293,0.194252,-0.030453,-0.021942
CAT AND MOUSE IN PARTNERSHIP,0.298423,0.085877,-0.203009,-0.176479,-0.024485
CAT-SKIN,-0.257714,-0.272870,0.269888,-0.161490,-0.165435
CLEVER ELSIE,0.007529,0.157363,-0.176414,-0.157475,-0.053896
...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811430,-0.110698,0.157723,-0.012236,-0.018325
THE WHITE SNAKE,-0.142344,-0.122723,0.046854,-0.066810,-0.084138
THE WILLOW-WREN AND THE BEAR,0.286673,0.116604,0.448459,0.029618,0.218151
THE WOLF AND THE SEVEN LITTLE KIDS,0.155384,0.532020,0.463433,0.208293,-0.036886
TOM THUMB,0.030407,0.312600,0.129061,0.266132,-0.261439

## Make Loading

In [7]:
LOADING = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
LOADING.columns = ["PC{}".format(i) for i in LOADING.columns]
LOADING.index = TFIDF.columns
LOADING.index.name = 'term_str'
LOADING.head()

               PC0       PC1       PC2       PC3       PC4
term_str
king     -0.054916 -0.067100  0.052543 -0.024533 -0.027711
man      -0.010365 -0.002341 -0.004306 -0.002939  0.003273
old       0.001096  0.003729  0.005118 -0.003182  0.001555
we       -0.001011  0.010648  0.003464 -0.003218 -0.001175
upon     -0.003012 -0.001604 -0.004466  0.009239 -0.001203

## Get Top 5 Postive Terms for PC0

In [8]:
LOADING.sort_values(by='PC0',ascending=False).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163085 -0.076818  0.021633 -0.005528  0.014361
cat       0.083831 -0.009637 -0.009444 -0.015528 -0.006639
mr        0.050418 -0.017043  0.001902 -0.005792  0.002883
wolf      0.048084  0.087003  0.081437  0.050046 -0.032398
mouse     0.021257  0.012197 -0.023731 -0.021045  0.000006

## Get Top 5 Negative Terms for PC1

In [9]:
LOADING.sort_values(by='PC1',ascending=True).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163085 -0.076818  0.021633 -0.005528  0.014361
king     -0.054916 -0.067100  0.052543 -0.024533 -0.027711
princess -0.018992 -0.043495  0.011589  0.036903 -0.009950
prince   -0.021698 -0.027671  0.007040  0.034937 -0.006605
twelve   -0.015512 -0.025068  0.014123  0.001676 -0.001397

## COMPS

In [10]:
# Got help from peer for this code
COMPS= pd.DataFrame(columns=['PC0_pole_1','PC0_pole_2','PC1_pole_1','PC1_pole_2','PC2_pole_1','PC2_pole_2','PC3_pole_1','PC3_pole_2','PC4_pole_1','PC4_pole_2'])
COMPS['PC0_pole_1'] = LOADING.sort_values(by='PC0',ascending=True).head(5).index.to_list()
COMPS['PC0_pole_2'] = LOADING.sort_values(by='PC0',ascending=True).tail(5).index.to_list()
COMPS['PC1_pole_1'] = LOADING.sort_values(by='PC1',ascending=True).head(5).index.to_list()
COMPS['PC1_pole_2'] = LOADING.sort_values(by='PC1',ascending=True).tail(5).index.to_list()
COMPS['PC2_pole_1'] = LOADING.sort_values(by='PC2',ascending=True).head(5).index.to_list()
COMPS['PC2_pole_2'] = LOADING.sort_values(by='PC1',ascending=True).tail(5).index.to_list()
COMPS['PC3_pole_1'] = LOADING.sort_values(by='PC3',ascending=True).head(5).index.to_list()
COMPS['PC3_pole_2'] = LOADING.sort_values(by='PC3',ascending=True).tail(5).index.to_list()
COMPS['PC4_pole_1'] = LOADING.sort_values(by='PC4',ascending=True).head(5).index.to_list()
COMPS['PC4_pole_2'] = LOADING.sort_values(by='PC4',ascending=True).tail(5).index.to_list()
COMPS

,PC0_pole_1,PC0_pole_2,PC1_pole_1,PC1_pole_2,PC2_pole_1,PC2_pole_2,PC3_pole_1,PC3_pole_2,PC4_pole_1,PC4_pole_2
0,king,mouse,fox,woman,mouse,woman,boy,dwarf,wolf,pearls
1,prince,wolf,king,shepherd,master,shepherd,king,thou,horse,bear
2,princess,mr,princess,mother,dog,mother,tower,prince,king,children
3,father,cat,prince,children,cellar,children,forest,princess,bride,brothers
4,dwarf,fox,twelve,wolf,money,wolf,cook,wolf,dog,dwarf

## Creating Visuals

### Getting DOC Table ready

In [11]:
DOC = DTM.sum(1).to_frame('n_tokens')
DOC['n_types'] = DTM.astype('bool').sum(1)
DOC['pkr'] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB['volume'])

In [12]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

In [13]:
NEW=DCM.join(DOC)
NEW

,PC0,PC1,PC2,PC3,PC4,n_tokens,n_types,pkr,volume
doc_title,,,,,,,,,
ASHPUTTEL,-0.149570,-0.118080,0.082594,0.067198,-0.198049,2589,506,0.195442,1
BRIAR ROSE,-0.225364,-0.240293,0.194252,-0.030453,-0.021942,1518,453,0.298419,1
CAT AND MOUSE IN PARTNERSHIP,0.298423,0.085877,-0.203009,-0.176479,-0.024485,985,344,0.349239,1
CAT-SKIN,-0.257714,-0.272870,0.269888,-0.161490,-0.165435,2136,470,0.220037,1
CLEVER ELSIE,0.007529,0.157363,-0.176414,-0.157475,-0.053896,1338,338,0.252616,1
...,...,...,...,...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811430,-0.110698,0.157723,-0.012236,-0.018325,376,174,0.462766,1
THE WHITE SNAKE,-0.142344,-0.122723,0.046854,-0.066810,-0.084138,1613,534,0.331060,1
THE WILLOW-WREN AND THE BEAR,0.286673,0.116604,0.448459,0.029618,0.218151,917,339,0.369684,2
THE WOLF AND THE SEVEN LITTLE KIDS,0.155384,0.532020,0.463433,0.208293,-0.036886,1102,336,0.304900,1
TOM THUMB,0.030407,0.312600,0.129061,0.266132,-0.261439,2541,612,0.240850,1

### Importing Functions

In [14]:
def vis_pcs(a, b,DCM, col='doc_label'):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DOC[col].astype('category'), 
        hover_name=DCM.index,
        marginal_x='box', 
        height=1000, 
        width=1200)
    return fig

In [15]:
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [16]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

### Visualize PCA 0 and 1

In [17]:
fig1=vis_pcs(0,1,NEW,col='volume')
fig1.write_image('output/p2591-PC1.png')
fig1.show()

The new additions in Volume II are all on the negative side for PC0 and PC1. Volume I is similar but also has stories that has more positive componets. This suggests that Volume I is more varied in PC0 and PC1 than Volume II.

### Visualize Loadings 0 and 1

In [18]:
fig2=vis_loadings(LOADING,0,1)
fig2.write_image('output/p2591-LOADING1.png')
fig2.show()

Most words seems to be in a huge cluster around the middle. There are some other clusters. For example the bottom left seems to have royal words like prince and kings. Right above the cluster seems to have family/identity words like mother and children.

## VIS PCA 2,3

In [19]:
fig3=vis_pcs(2,3,NEW,col='volume')
fig3.write_image('output/p2591-PC2.png')
fig3.show()

Both Volume I and Volume II seem to be well to be evenly distriuted around PC2 and PC3 with even spread in the postive and negative side. Again Volume II is less varied - as it has a shorter whiskser - with PC2 and PC3 values, this could be due to Volume II having less stories

## VIS LOADINGS 2,3

In [20]:
fig4=vis_loadings(LOADING,2,3)
fig4.write_image('output/p2591-LOADING2.png')
fig4.show()

Like the last loading, this one also have a huge clusters around the origin and several smaller clusters. This one seems to more smaller custers than the loadings of PC0 and PC1. I did notice similar separatuion class. Working class terms - cookm huntsmen, etc -have negative PC3 value, while prince and princess - royal words - are on the postive side of PC3. There are clear outliers though with king and queen having negative PC3. SO maybe these PC are a bit more complex than just social class.

## Save Files

In [21]:
# COMPS.to_csv('output/p2591-comps.csv')
# LOADING.to_csv('output/p2591-loading.csv')

In [22]:
DCM.to_csv('output/p2591-dcm_pca.csv')