# Principal Component Analysis of Grimm Brothers

## Setup and Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import normalize
from sklearn.decomposition import PCA, TruncatedSVD as SVD

In [2]:
import plotly.express as px
import plotly.io as pio

In [3]:
TFIDF = pd.read_csv('data/pg2591-TFIDF.csv',index_col=0)
TFIDF.head()

,king,man,old,we,upon,father,himself,shall,take,cried,...,appear,cooking,grass,backwards,finding,doors,sides,searched,started,hide
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0.111674,0.004770,0.00420,0.004200,0.014623,0.102368,0.011775,0.014623,0.010177,0.021935,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.028603
BRIAR ROSE,0.263257,0.017991,0.06337,0.000000,0.041367,0.000000,0.000000,0.020683,0.012795,0.006894,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT AND MOUSE IN PARTNERSHIP,0.000000,0.000000,0.00000,0.038154,0.004744,0.000000,0.000000,0.009488,0.004402,0.014232,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
CAT-SKIN,0.452256,0.000000,0.00000,0.021486,0.014026,0.035704,0.000000,0.004675,0.026031,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.036579
CLEVER ELSIE,0.000000,0.038482,0.00000,0.081325,0.000000,0.030031,0.000000,0.035392,0.000000,0.011797,...,0.046151,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [4]:
DTM = pd.read_csv('data/pg2591-DTM.csv',index_col=0)
DTM.head()

,1,2,3,_jug,_my_,a,abashed,abide,able,abode,...,yonder,you,young,younger,youngest,your,yours,yourself,yourselves,youth
doc_title,,,,,,,,,,,,,,,,,,,,,
ASHPUTTEL,0,0,0,0,1,21,0,0,0,0,...,0,24,0,0,0,3,0,0,0,0
BRIAR ROSE,0,0,0,0,0,33,0,0,0,0,...,0,2,1,0,0,2,0,0,0,0
CAT AND MOUSE IN PARTNERSHIP,0,0,0,0,0,17,0,0,0,0,...,0,21,0,0,0,4,1,1,0,0
CAT-SKIN,0,0,0,0,0,46,0,0,0,0,...,0,20,0,0,0,1,0,0,0,0
CLEVER ELSIE,0,0,0,0,0,23,0,0,0,0,...,0,4,0,0,0,0,0,0,0,0

In [5]:
LIB = pd.read_csv('data/pg2591-LIB.csv',index_col=0)
LIB.head()

                          volume
doc_title
THE GOLDEN BIRD                1
HANS IN LUCK                   1
JORINDA AND JORINDEL           1
THE TRAVELLING MUSICIANS       1
OLD SULTAN                     1

## DCM

In [6]:
pca_engine = PCA(n_components=5)
DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF), index=TFIDF.index)
DCM.columns = ['PC{}'.format(i) for i in DCM.columns]
DCM

,PC0,PC1,PC2,PC3,PC4
doc_title,,,,,
ASHPUTTEL,-0.149581,-0.118294,0.082564,0.070627,-0.200862
BRIAR ROSE,-0.225403,-0.240635,0.195472,-0.039215,-0.019006
CAT AND MOUSE IN PARTNERSHIP,0.298401,0.085867,-0.200428,-0.184978,-0.028195
CAT-SKIN,-0.257751,-0.273233,0.271747,-0.170375,-0.161650
CLEVER ELSIE,0.007610,0.156629,-0.178805,-0.155302,-0.045997
...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811432,-0.110870,0.158091,-0.015066,-0.016140
THE WHITE SNAKE,-0.142415,-0.122882,0.054349,-0.068704,-0.094140
THE WILLOW-WREN AND THE BEAR,0.286636,0.116886,0.444846,0.033074,0.218201
THE WOLF AND THE SEVEN LITTLE KIDS,0.155384,0.531522,0.468446,0.202925,-0.044182
TOM THUMB,0.030424,0.312862,0.127648,0.270884,-0.259961

In [7]:
## Make Loading

In [8]:
LOADING = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_))
LOADING.columns = ["PC{}".format(i) for i in LOADING.columns]
LOADING.index = TFIDF.columns
LOADING.index.name = 'term_str'
LOADING.head()

               PC0       PC1       PC2       PC3       PC4
term_str
king     -0.054922 -0.067133  0.052849 -0.025818 -0.027503
man      -0.010362 -0.002311 -0.004610 -0.002519  0.003607
old       0.001096  0.003778  0.004930 -0.002974  0.001270
we       -0.001010  0.010654  0.003260 -0.002994 -0.000560
upon     -0.003012 -0.001561 -0.004667  0.009497 -0.000803

## Get Top 5 Postive Terms for PC0

In [9]:
LOADING.sort_values(by='PC0',ascending=False).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163089 -0.076814  0.021487 -0.004717  0.013643
cat       0.083834 -0.009601 -0.010021 -0.016396 -0.004090
mr        0.050425 -0.017038  0.001298 -0.005429  0.004445
wolf      0.048071  0.086918  0.082591  0.048667 -0.033528
mouse     0.021246  0.012183 -0.022778 -0.021678 -0.002804

## Get Top 5 Negatuve Terms for PC1

In [10]:
LOADING.sort_values(by='PC1',ascending=True).head(5)

               PC0       PC1       PC2       PC3       PC4
term_str
fox       0.163089 -0.076814  0.021487 -0.004717  0.013643
king     -0.054922 -0.067133  0.052849 -0.025818 -0.027503
princess -0.018997 -0.043510  0.012768  0.035781 -0.010524
prince   -0.021691 -0.027729  0.006921  0.035147 -0.006417
twelve   -0.015520 -0.025089  0.014138  0.000726 -0.001213

## Creating Visuals

## Getting DOC Table ready

In [11]:
DOC = DTM.sum(1).to_frame('n_tokens')
DOC['n_types'] = DTM.astype('bool').sum(1)
DOC['pkr'] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB['volume'])

In [12]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

In [13]:
NEW=DCM.join(DOC)
NEW

,PC0,PC1,PC2,PC3,PC4,n_tokens,n_types,pkr,volume
doc_title,,,,,,,,,
ASHPUTTEL,-0.149581,-0.118294,0.082564,0.070627,-0.200862,2589,506,0.195442,1
BRIAR ROSE,-0.225403,-0.240635,0.195472,-0.039215,-0.019006,1518,453,0.298419,1
CAT AND MOUSE IN PARTNERSHIP,0.298401,0.085867,-0.200428,-0.184978,-0.028195,985,344,0.349239,1
CAT-SKIN,-0.257751,-0.273233,0.271747,-0.170375,-0.161650,2136,470,0.220037,1
CLEVER ELSIE,0.007610,0.156629,-0.178805,-0.155302,-0.045997,1338,338,0.252616,1
...,...,...,...,...,...,...,...,...,...
THE WEDDING OF MRS. FOX - PART II,0.811432,-0.110870,0.158091,-0.015066,-0.016140,376,174,0.462766,1
THE WHITE SNAKE,-0.142415,-0.122882,0.054349,-0.068704,-0.094140,1613,534,0.331060,1
THE WILLOW-WREN AND THE BEAR,0.286636,0.116886,0.444846,0.033074,0.218201,917,339,0.369684,2
THE WOLF AND THE SEVEN LITTLE KIDS,0.155384,0.531522,0.468446,0.202925,-0.044182,1102,336,0.304900,1
TOM THUMB,0.030424,0.312862,0.127648,0.270884,-0.259961,2541,612,0.240850,1

### Importing Functions

In [14]:
def vis_pcs(a, b,DCM, col='doc_label'):
    fig =px.scatter(DCM, 
        f"PC{a}", f"PC{b}", 
        color=DOC[col].astype('category'), 
        hover_name=DCM.index,
        marginal_x='box', 
        height=1000, 
        width=1200)
    fig.show()

In [15]:
def vis_loadings(COMPS, a=0, b=1, hover_name='term_str'):
    return px.scatter(COMPS.reset_index(), f"PC{a}", f"PC{b}", 
                      text='term_str', 
                      marginal_x='box', 
                      height=800)

In [16]:
DOC.head()

                              n_tokens  n_types       pkr  volume
doc_title
ASHPUTTEL                         2589      506  0.195442       1
BRIAR ROSE                        1518      453  0.298419       1
CAT AND MOUSE IN PARTNERSHIP       985      344  0.349239       1
CAT-SKIN                          2136      470  0.220037       1
CLEVER ELSIE                      1338      338  0.252616       1

### Visualize PCA

In [17]:
vis_pcs(0,1,NEW,col='volume')

The new additions in Volume II are all on the negative side for PC0 and PC1. Volume I is similar but also has stories that has more positive componets. This suggests that Volume I is more varied in PC0 and PC1 than Volume II.

### Visualize Loadings

In [18]:
vis_loadings(LOADING,0,1)

Most words seems to be in a huge cluster around the middle. There are some other clusters. For example the bottom left seems to have royal words like prince and kings. Right above the cluster seems to have family/identity words like mother and children.