# Sentiment Analyis of Grimm Brothers

## Setup and Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, HTML

In [14]:
OHCO = ['doc_title','para_num','sentence_num','token_num']

In [7]:
# Import SALEX from kaggle for sentiment analysis
emo_cols = "anger anticipation disgust fear joy sadness surprise trust sentiment".split()
SALEX = pd.read_csv('data/salex_nrc.csv').set_index('term_str')
SALEX.columns = [col.replace('nrc_','') for col in SALEX.columns]
SALEX.head()

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust,sentiment
term_str,,,,,,,,,,,
abandon,0,0,0,1,0,1,0,1,0,0,-1
abandoned,1,0,0,1,0,1,0,1,0,0,-1
abandonment,1,0,0,1,0,1,0,1,1,0,-1
abduction,0,0,0,1,0,1,0,1,1,0,-1
aberration,0,0,1,0,0,1,0,0,0,0,-1

In [8]:
DOCS = pd.read_csv('data/pg2591-DOCS.csv')
DOCS.head()

,doc_id,doc_title,doc_str
0,1,THE GOLDEN BIRD,"\n\nA certain king had a beautiful garden, and..."
1,2,HANS IN LUCK,\n\nSome men are born to good luck: all they d...
2,3,JORINDA AND JORINDEL,"\n\nThere was once an old castle, that stood i..."
3,4,THE TRAVELLING MUSICIANS,\n\nAn honest farmer had once an ass that had ...
4,5,OLD SULTAN,"\n\nA shepherd had a faithful dog, called Sult..."

In [15]:
TOKENS= pd.read_csv('/Users/graceegeorge/TextasDataFinalProject/data/p2591-TOKENS.csv').set_index(OHCO).dropna()
TOKENS.head()

                                                pos_tuple pos token_str  \
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0           ('The', 'DT')  DT       The
                                1          ('wife', 'NN')  NN      wife
                                2            ('of', 'IN')  IN        of
                                3             ('a', 'DT')  DT         a
                                4          ('rich', 'JJ')  JJ      rich

                                          term_str pos_group
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0              the        DT
                                1             wife        NN
                                2               of        IN
                                3                a        DT
                                4             rich        JJ

In [9]:
VOCAB = pd.read_csv('data/pg2591-VOCAB.csv')
VOCAB.head()

,term_str,n,p,i,n_chars,max_pos_group,max_pos,p_stem,stop
0,the,6927,0.068553,3.866638,3,DT,DT,the,1
1,and,5433,0.053768,4.217119,3,CC,CC,and,1
2,to,2662,0.026344,5.246358,2,TO,TO,to,1
3,he,2093,0.020713,5.593296,2,PR,PRP,he,1
4,a,1909,0.018892,5.726051,1,DT,DT,a,1

## Get VOCAB sentiment analysis

In [ ]:
# Conducted on token table by following example "Sentiment Analysis with Novels"
VOCAB_SA = TOKENS.join(SALEX, on='term_str', how='left') #.fillna(0)
VOCAB_SA

                                                 pos_tuple  pos token_str  \
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0            ('The', 'DT')   DT       The
                                1           ('wife', 'NN')   NN      wife
                                2             ('of', 'IN')   IN        of
                                3              ('a', 'DT')   DT         a
                                4           ('rich', 'JJ')   JJ      rich
...                                                    ...  ...       ...
TOM THUMB 21       3            40            ('s', 'VBZ')  VBZ         s
                                41            ('no', 'DT')   DT        no
                                42         ('place', 'NN')   NN     place
                                43          ('like', 'IN')   IN      like
                                44          ('HOME', 'NN')   NN      HOME

                                          term_str pos_group  anger  \
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0              the        DT    NaN
                                1             wife        NN    NaN
                                2               of        IN    NaN
                                3                a        DT    NaN
                                4             rich        JJ    NaN
...                                            ...       ...    ...
TOM THUMB 21       3            40               s        VB    NaN
                                41              no        DT    NaN
                                42           place        NN    NaN
                                43            like        IN    NaN
                                44            home        NN    NaN

                                           anticipation  disgust  fear  joy  \
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0                   NaN      NaN   NaN  NaN
                                1                   NaN      NaN   NaN  NaN
                                2                   NaN      NaN   NaN  NaN
                                3                   NaN      NaN   NaN  NaN
                                4                   NaN      NaN   NaN  NaN
...                                                 ...      ...   ...  ...
TOM THUMB 21       3            40                  NaN      NaN   NaN  NaN
                                41                  NaN      NaN   NaN  NaN
                                42                  NaN      NaN   NaN  NaN
                                43                  NaN      NaN   NaN  NaN
                                44                  NaN      NaN   NaN  NaN

                                           negative  positive  sadness  \
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0               NaN       NaN      NaN
                                1               NaN       NaN      NaN
                                2               NaN       NaN      NaN
                                3               NaN       NaN      NaN
                                4               NaN       NaN      NaN
...                                             ...       ...      ...
TOM THUMB 21       3            40              NaN       NaN      NaN
                                41              NaN       NaN      NaN
                                42              NaN       NaN      NaN
                                43              NaN       NaN      NaN
                                44              NaN       NaN      NaN

                                           surprise  trust  sentiment
doc_title para_num sentence_num token_num
ASHPUTTEL 0        0            0               NaN    NaN        NaN
                                1               NaN    NaN        NaN
                                2               NaN    NaN        NaN
                                3               NaN    NaN        NaN
                                4               NaN    NaN        NaN
...                                             ...    ...        ...
TOM THUMB 21       3            40              NaN    NaN        NaN
                                41              NaN    NaN        NaN
                                42              NaN    NaN        NaN
                                43              NaN    NaN        NaN
                                44              NaN    NaN        NaN

[101046 rows x 16 columns]

## Turn in BOW_SA (BOW = STORIES)

In [17]:
STORIES_SA = VOCAB_SA.fillna(0).groupby('doc_title')[emo_cols].mean()
STORIES_SA.head()

,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,sentiment
doc_title,,,,,,,,,
ASHPUTTEL,0.005794,0.019699,0.007725,0.006566,0.033217,0.016222,0.005794,0.026651,0.010815
BRIAR ROSE,0.006588,0.017128,0.003953,0.009223,0.023715,0.011199,0.009881,0.013834,0.010540
CAT AND MOUSE IN PARTNERSHIP,0.001015,0.030457,0.011168,0.003046,0.032487,0.014213,0.007107,0.035533,0.023350
CAT-SKIN,0.006554,0.015449,0.006554,0.007022,0.028558,0.013109,0.010300,0.018727,0.009831
CLEVER ELSIE,0.005979,0.012706,0.006726,0.011211,0.021674,0.021674,0.005979,0.012706,-0.004484